version: "3.8"
services:
  postgres-services:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - vending-machine:/data/postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: banana
      POSTGRES_DB: vending-machine

  backend-nest:
    build:
      context: ./backend
      dockerfile: dockerfile
      args:
        - NODE_ENV=development
    ports:
      - 3001:3001
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      DATABASE_URL: "postgres://admin:banana@postgres-services:5432/vending-machine"
      NODE_ENV: development
      PORT: 3001
    depends_on:
      - postgres-services

  client-backoffice:
    stdin_open: true
    tty: true
    build:
      context: ./client-backoffice
      dockerfile: dockerfile
    ports:
      - "3002:3000"
    volumes:
      - /app/node_modules
      - ./client-backoffice:/app
    depends_on:
      - backend-nest
    environment:
      API_URL: backend-nest

  # client-machine:
  #   stdin_open: true
  #   tty: true
  #   build:
  #     context: ./client-machine
  #     dockerfile: dockerfile
  #   ports:
  #     - "3002:3000"
  #   volumes:
  #     - /app/node_modules
  #     - ./client-machine:/app
  #   depends_on:
  #     - backend-nest
  #   environment:
  #     API_URL: backend-nest

volumes:
  vending-machine:
